import contextlib
import importlib.machinery
import io
import json
import shutil
import tempfile
import unittest
from pathlib import Path

FIX = Path("tests/fixtures/designer/project")
FIX_FSD = Path("tests/fixtures/designer/project-fsd")
L = importlib.machinery.SourceFileLoader("designer_gallery", "bin/designer-gallery").load_module()

HEADER = "generated by designer-gallery; do not edit"


def prepared():
    tmp = Path(tempfile.mkdtemp()) / "project"
    shutil.copytree(FIX, tmp)
    return tmp


def run_gallery(mockups_dir, map_path):
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        try:
            code = L.main([str(mockups_dir), "--map", str(map_path)])
        except SystemExit as exc:
            code = exc.code if isinstance(exc.code, int) else (0 if exc.code is None else 1)
    return code, out.getvalue(), err.getvalue()


class DesignerGallery(unittest.TestCase):
    def test_refuses_on_red_manifest(self):
        proj = prepared()
        manifest = proj / "mockups" / "mockups.json"
        data = json.loads(manifest.read_text())
        del data["mockups"]["mockup:clients/legacy"]
        manifest.write_text(json.dumps(data))
        sentinel = proj / "mockups" / "index.html"
        sentinel.write_text("old\n")
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertNotEqual(code, 0)
        self.assertIn("screen:clients/other", err)
        self.assertEqual(sentinel.read_text(), "old\n")
        self.assertFalse((proj / "mockups" / "MOCKUPS.md").exists())

    def test_generates_index_and_mirror(self):
        proj = prepared()
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        index = proj / "mockups" / "index.html"
        mirror = proj / "mockups" / "MOCKUPS.md"
        self.assertTrue(index.exists())
        self.assertTrue(mirror.exists())
        self.assertIn(HEADER, index.read_text().splitlines()[0])
        self.assertIn(HEADER, mirror.read_text().splitlines()[0])
        self.assertIn("Clients.dc.html", index.read_text())

    def test_idempotent(self):
        proj = prepared()
        mockups = proj / "mockups"
        run_gallery(mockups, proj / "MAP.md")
        first = {p.name: p.read_bytes() for p in (mockups / "index.html", mockups / "MOCKUPS.md")}
        code, _, err = run_gallery(mockups, proj / "MAP.md")
        self.assertEqual(code, 0, err)
        second = {p.name: p.read_bytes() for p in (mockups / "index.html", mockups / "MOCKUPS.md")}
        self.assertEqual(first, second)

    def test_mockups_md_mirrors_manifest(self):
        proj = prepared()
        run_gallery(proj / "mockups", proj / "MAP.md")
        text = (proj / "mockups" / "MOCKUPS.md").read_text()
        self.assertIn("- mockup:clients/clients -> Clients.dc.html (screen: screen:clients/clients)", text)
        self.assertIn("- mockup:clients/legacy -> Legacy.dc.html (screen: screen:clients/other)", text)
        self.assertNotIn("Not mocked", text)

        manifest = proj / "mockups" / "mockups.json"
        data = json.loads(manifest.read_text())
        del data["mockups"]["mockup:clients/legacy"]
        data["none"] = ["screen:clients/other"]
        manifest.write_text(json.dumps(data))
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        text = (proj / "mockups" / "MOCKUPS.md").read_text()
        self.assertIn("## Not mocked", text)
        self.assertIn("- screen:clients/other", text)

    def test_feature_view_per_feature(self):
        proj = prepared()
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        view = proj / "mockups" / "feature" / "clients.html"
        self.assertTrue(view.exists())
        text = view.read_text()
        self.assertIn(HEADER, text.splitlines()[0])
        # Views live in feature/, so the artboard href must climb one level.
        self.assertIn('href="../Clients.dc.html"', text)
        self.assertIn("../index.html", text)

    def test_fallback_to_map_section(self):
        proj = prepared()
        manifest = proj / "mockups" / "mockups.json"
        data = json.loads(manifest.read_text())
        del data["mockups"]["mockup:clients/clients"]["feature"]
        manifest.write_text(json.dumps(data))
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        text = (proj / "mockups" / "feature" / "clients.html").read_text()
        self.assertIn("Clients.dc.html", text)

    def test_fsd_design_overrides_section(self):
        proj = prepared()
        shutil.copy(FIX_FSD / "fsd-design.md", proj / "fsd-design.md")
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        text = (proj / "mockups" / "feature" / "support-tools.html").read_text()
        self.assertIn("Legacy.dc.html", text)
        clients = (proj / "mockups" / "feature" / "clients.html").read_text()
        self.assertIn("Clients.dc.html", clients)

    def test_map_view_arrows(self):
        proj = prepared()
        # Place the linked target on the canvas too so the SVG edge renders.
        canvas = proj / "mockups" / "canvas.json"
        data = json.loads(canvas.read_text())
        data["artboards"].append(
            {"file": "Legacy.dc.html", "title": "Legacy", "feature": "clients", "x": 1600, "y": 0, "w": 1440, "h": 900}
        )
        canvas.write_text(json.dumps(data))
        artboard = proj / "mockups" / "Clients.dc.html"
        text = artboard.read_text()
        artboard.write_text(text.replace("</body>", '<p><a href="Other.dc.html">next</a></p></body>'))
        legacy = proj / "mockups" / "Legacy.dc.html"
        legacy.write_text(legacy.read_text().replace("</body>", '<p><a href="Clients.dc.html">back</a></p></body>'))
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        map_text = (proj / "mockups" / "map.html").read_text()
        self.assertIn(HEADER, map_text.splitlines()[0])
        self.assertIn('{"from": "Clients.dc.html", "to": "Other.dc.html"}', map_text)
        # The placed pair renders as an SVG arrowhead line; the unplaced target only.
        self.assertIn('data-from="Legacy.dc.html" data-to="Clients.dc.html"', map_text)
        self.assertIn('marker-end="url(#arrow)"', map_text)

    def test_idempotent_still_holds(self):
        proj = prepared()
        mockups = proj / "mockups"
        run_gallery(mockups, proj / "MAP.md")
        names = ("index.html", "MOCKUPS.md", "map.html", "feature/clients.html")
        first = {n: (mockups / n).read_bytes() for n in names}
        code, _, err = run_gallery(mockups, proj / "MAP.md")
        self.assertEqual(code, 0, err)
        second = {n: (mockups / n).read_bytes() for n in names}
        self.assertEqual(first, second)

    def test_sectionless_screen_lands_in_misc(self):
        proj = prepared()
        # A screen row above the first Section: heading passes the validator
        # gate (rows are section-agnostic) but has no enclosing section.
        map_path = proj / "MAP.md"
        row = "| screen:clients/extra | /clients/extra | tool | | get /api/clients/extra | green | Extra |"
        map_path.write_text(map_path.read_text().replace("Section: Clients", f"{row}\n\nSection: Clients", 1))
        manifest = proj / "mockups" / "mockups.json"
        data = json.loads(manifest.read_text())
        data["mockups"]["mockup:clients/extra"] = {"artboard": "Legacy", "screen": "screen:clients/extra"}
        manifest.write_text(json.dumps(data))
        code, _, err = run_gallery(proj / "mockups", map_path)
        self.assertEqual(code, 0, err)
        misc = proj / "mockups" / "feature" / "misc.html"
        self.assertTrue(misc.exists())
        self.assertIn('href="../Legacy.dc.html"', misc.read_text())

    def test_link_derivation_ignores_external_and_keeps_fragments(self):
        proj = prepared()
        artboard = proj / "mockups" / "Clients.dc.html"
        artboard.write_text(artboard.read_text().replace(
            "</body>",
            "<p>"
            '<a href="HTTPS://EXAMPLE.COM/Up.dc.html">up</a>'
            '<a href="//cdn.example.com/Ext.dc.html">ext</a>'
            '<a href="Other.dc.html#top">top</a>'
            '<a href="Other.dc.html?v=2">query</a>'
            "</p></body>",
        ))
        code, _, err = run_gallery(proj / "mockups", proj / "MAP.md")
        self.assertEqual(code, 0, err)
        map_text = (proj / "mockups" / "map.html").read_text()
        # Fragment/query hrefs still resolve to the artboard target.
        self.assertIn('{"from": "Clients.dc.html", "to": "Other.dc.html"}', map_text)
        # Uppercase-scheme and protocol-relative hrefs never become targets.
        self.assertNotIn("Up.dc.html", map_text)
        self.assertNotIn("Ext.dc.html", map_text)


if __name__ == "__main__":
    unittest.main()
