"""Recipes for generated files, applied by hand, must equal tools/generate.py output."""
import datetime
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "kits/workspace/tools"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from workspace_helpers import DEFAULT_PARAMS, create_workspace, run_generate  # noqa: E402

PROFILE_DIR = ".agents/profiles/ui-migration"
PROJECT = "demo"
BREAKDOWN_DEFAULTS = {"title": "Breakdown of",
                      "note": "Generated by tools/generate.py from stories/*/story.md. Do not edit.",
                      "columns": ["Story", "Wave", "Scope", "Unmapped", "Tracker", "Depends"]}


def tree_bytes(root):
    # __pycache__ holds interpreter bytecode whose header embeds source mtimes, so it differs between any two workspaces.
    return {p.relative_to(root).as_posix(): p.read_bytes()
            for p in sorted(root.rglob("*"))
            if p.is_file() and not {".git", "__pycache__"} & set(p.relative_to(root).parts)}


def write(ws, rel, text):
    path = ws / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def add_repository_source(ws, entry):
    manifest = json.loads((ws / "repos.json").read_text(encoding="utf-8"))
    manifest["repositories"].append(entry)
    write(ws, "repos.json", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")


def recipe_repository(ws, entry):
    text = (ws / "REPOSITORIES.md").read_text(encoding="utf-8")
    row = "| %s | %s | %s | %s | %s |" % (
        entry["name"], entry["forge"], entry["default_branch"],
        entry.get("kit", {}).get("kind", ""), entry["summary"])
    end = "<!-- repos:end -->"
    assert text.count(end) == 1
    write(ws, "REPOSITORIES.md", text.replace(end, row + "\n" + end))


def recipe_adr(ws, number, slug):
    rel = ".agents/index.json"
    text = (ws / rel).read_text(encoding="utf-8")
    entry = '  "adr:%s": "docs/adr/%s-%s.md"' % (number, number, slug)
    if text == "{}\n":
        write(ws, rel, "{\n" + entry + "\n}\n")
        return
    lines = text.split("\n")
    adr_lines = [i for i, line in enumerate(lines) if line.startswith('  "adr:')]
    pos = adr_lines[-1] + 1 if adr_lines else lines.index("{") + 1
    before, after = lines[pos - 1], lines[pos]
    if before.startswith("  ") and not before.endswith(","):
        lines[pos - 1] = before + ","
    if after.startswith("  "):
        entry += ","
    lines.insert(pos, entry)
    write(ws, rel, "\n".join(lines))


def recipe_skill(ws, name):
    # The literal commands from the skill recipe in .agents/skills/extend/SKILL.md.
    commands = [
        "mkdir -p .claude/skills/{n} && cp -R .agents/skills/{n}/. .claude/skills/{n}/",
        "find .claude/skills/{n} -name .DS_Store -type f -delete",
        "find .claude/skills/{n} -name __pycache__ -type d -prune -exec rm -rf {{}} +",
    ]
    for command in commands:
        subprocess.run(command.format(n=name), shell=True, cwd=ws, check=True)


def recipe_agent(ws, name):
    source = (ws / ".agents/agents" / (name + ".md")).read_text(encoding="utf-8")
    write(ws, ".claude/agents/%s.md" % name, source)
    lines = source.split("\n")
    close = lines.index("---", 1)
    description = next(line for line in lines[1:close] if line.startswith("description:"))
    body = "\n".join(lines[close + 1:])
    write(ws, ".opencode/agents/%s.md" % name, "---\n" + description + "\nmode: subagent\n---\n" + body)


def recipe_rule(ws, name):
    source = (ws / ".agents/rules" / (name + ".md")).read_text(encoding="utf-8")
    first = source.split("\n", 1)[0]
    header = "---\ndescription: " + first[len("# "):] + "\nalwaysApply: true\n---\n"
    write(ws, ".cursor/rules/%s.mdc" % name, header + source)


SCREEN_FIELDS = ["key", "route", "kind", "section", "parent", "access", "label", "wave", "story"]


def unquote(value):
    return value[1:-1] if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'" else value


def frontmatter_values(text):
    """Frontmatter values as cell strings: verbatim scalars without surrounding quotes, lists joined with ", ", empty as ""."""
    lines = text.split("\n")
    close = lines.index("---", 1)
    values, last = {}, None
    for line in lines[1:close]:
        if line.startswith("  - "):
            values[last] = (values[last] + ", " if values[last] else "") + unquote(line[len("  - "):].strip())
            continue
        name, _, value = line.partition(":")
        value = value.strip()
        values[name] = "" if value == "[]" else ", ".join(unquote(v.strip()) for v in value[1:-1].split(",")) \
            if value.startswith("[") else unquote(value)
        last = name
    return values


def workspace_language(ws):
    """params.language of .agents/kit.json, en when absent."""
    return json.loads((ws / ".agents/kit.json").read_text(encoding="utf-8")).get("params", {}).get("language", "en")


def in_language(value, language):
    """The language value of a profile language object, its en value without that key; a plain value as is."""
    return value.get(language, value["en"]) if isinstance(value, dict) else value


def profile(ws):
    return json.loads((ws / PROFILE_DIR / "profile.json").read_text(encoding="utf-8"))


def profile_template(ws, name):
    """The profile template <name>.<language>.md when it exists for a non-en language, else <name>.md."""
    language = workspace_language(ws)
    localized = ws / PROFILE_DIR / ("%s.%s.md" % (name, language))
    path = localized if language != "en" and localized.exists() else ws / PROFILE_DIR / (name + ".md")
    return path.read_text(encoding="utf-8")


def screen_table(ws):
    """Heading and columns of the screen element table, in the workspace language."""
    table = profile(ws)["elements"][0]["tables"][0]
    language = workspace_language(ws)
    return in_language(table["heading"], language), in_language(table["columns"], language)


def from_column(ws):
    """map_doc.from_column in the workspace language, From when absent."""
    return in_language(profile(ws).get("map_doc", {}).get("from_column", "From"), workspace_language(ws))


def set_from_column(ws, value):
    data = profile(ws)
    data["map_doc"]["from_column"] = value
    write(ws, PROFILE_DIR + "/profile.json", json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def add_domain(ws, domain):
    write(ws, "projects/%s/domains/%s/MAP.md" % (PROJECT, domain),
          profile_template(ws, "MAP").replace("<domain>", domain))
    write(ws, "projects/%s/domains/%s/map/.gitkeep" % (PROJECT, domain), "")


def add_screen(ws, domain, slug, route, parent, wave, transitions):
    """### Recipe: map element, steps map-element.1-3 of .agents/skills/extend/SKILL.md: fill the profile's screen template."""
    rows = "".join("| %s | %s |\n" % t for t in transitions)
    filled = (profile_template(ws, "screen")
              .replace("<project>/<domain>/<slug>", "%s/%s/%s" % (PROJECT, domain, slug))
              .replace("/<route>", route)
              .replace("<section>", "Risks")
              .replace("parent:\n", "parent: %s\n" % parent)
              .replace("<spec operation>", "%s.read" % slug)
              .replace("<legacy menu label>", slug.title())
              .replace("wave: 1\n", "wave: %s\n" % wave))
    write(ws, "projects/%s/domains/%s/map/%s.md" % (PROJECT, domain, slug), filled + rows)


def add_stream(ws, domain, stream, stage="goal"):
    text = (ws / ".agents/templates/stream.json").read_text(encoding="utf-8")
    text = (text.replace("<domain>/<stream>", "%s/%s/%s" % (PROJECT, domain, stream))
                .replace('"goal"', '"%s"' % stage))
    write(ws, "projects/%s/domains/%s/streams/%s/stream.json" % (PROJECT, domain, stream), text)


def story_rel(domain, stream, slug):
    return "projects/%s/domains/%s/streams/%s/stories/%s/story.md" % (PROJECT, domain, stream, slug)


def add_story(ws, domain, stream, slug, wave, scope=(), unmapped=None, depends=(), tracker="", waiting=False):
    def block(field, keys):
        return field + ":\n" + "".join("  - %s\n" % k for k in keys) if keys else field + ": []\n"

    template = profile_template(ws, "story")
    body = template[template.index("\n---\n", 4) + len("\n---\n"):]
    head = ("---\nkey: story:%s/%s/%s\ntype: story\n" % (PROJECT, domain, slug)
            + ("status: waiting\nowner:\nstarted:\n" if waiting else "")
            + "wave: %s\ntracker:%s\n" % (wave, " " + tracker if tracker else "")
            + block("scope", scope) + ("unmapped: %s\n" % unmapped if unmapped else "")
            + block("depends", depends) + "repos: []\ndecisions: []\nmockups: []\n---\n")
    write(ws, story_rel(domain, stream, slug), head + body)


def flip_story(ws, domain, stream, slug, owner, started):
    """Step 9 of .agents/skills/task-start/SKILL.md: the three frontmatter lines a start writes."""
    text = (ws / story_rel(domain, stream, slug)).read_text(encoding="utf-8")
    for old, new in (("status: waiting\n", "status: in_progress\n"),
                     ("owner:\n", "owner: %s\n" % owner),
                     ("started:\n", "started: %s\n" % started)):
        assert text.count(old) == 1, old
        text = text.replace(old, new)
    write(ws, story_rel(domain, stream, slug), text)


def set_screen_story(ws, domain, slug, story_key):
    rel = "projects/%s/domains/%s/map/%s.md" % (PROJECT, domain, slug)
    text = (ws / rel).read_text(encoding="utf-8")
    assert text.count("\nstory:\n") == 1
    write(ws, rel, text.replace("\nstory:\n", "\nstory: %s\n" % story_key))


def _block_bounds(lines, name):
    return lines.index("<!-- map:%s:begin -->" % name), lines.index("<!-- map:%s:end -->" % name)


def _row_file_name(row):
    # A row's element file name comes from its first cell, the key `screen:<project>/<domain>/<slug>`.
    return row.split(" | ", 1)[0][len("| "):].rsplit("/", 1)[1] + ".md"


def recipe_map_element(ws, domain, slug):
    """### Recipe: map element in .agents/skills/extend/SKILL.md, step 5."""
    rel = "projects/%s/domains/%s/MAP.md" % (PROJECT, domain)
    source = (ws / ("projects/%s/domains/%s/map/%s.md" % (PROJECT, domain, slug))).read_text(encoding="utf-8")
    values = frontmatter_values(source)
    new_name = slug + ".md"
    heading, columns = screen_table(ws)
    table_block = heading.lower().replace(" ", "-")
    screen_row = "| " + " | ".join(values.get(f, "") for f in SCREEN_FIELDS) + " |"
    table = source.split("## %s\n" % heading, 1)[1].split("\n")[2:]
    transition_rows = ["| %s | %s |" % (values["key"], " | ".join(c.strip() for c in line.strip("|").split("|")))
                       for line in table if line.startswith("|")]
    headers = {
        "screens": ["| " + " | ".join(SCREEN_FIELDS) + " |", "|" + "---|" * len(SCREEN_FIELDS)],
        table_block: ["| " + from_column(ws) + " | " + " | ".join(columns) + " |", "|" + "---|" * (len(columns) + 1)],
    }
    lines = (ws / rel).read_text(encoding="utf-8").split("\n")
    for name, new_rows in (("screens", [screen_row]), (table_block, transition_rows)):
        begin, end = _block_bounds(lines, name)
        if end == begin + 1:
            lines[end:end] = headers[name]
            end += 2
        pos = next((i for i in range(begin + 3, end) if _row_file_name(lines[i]) > new_name), end)
        lines[pos:pos] = new_rows
    write(ws, rel, "\n".join(lines))


def recipe_story_cell(ws, domain, element_key, story_key):
    """The MAP.md story cell change of step 14 in .agents/skills/task-new/SKILL.md."""
    rel = "projects/%s/domains/%s/MAP.md" % (PROJECT, domain)
    lines = (ws / rel).read_text(encoding="utf-8").split("\n")
    begin, end = _block_bounds(lines, "screens")
    column = [c.strip() for c in lines[begin + 1].strip("|").split("|")].index("story")
    row = next(i for i in range(begin + 3, end) if lines[i].startswith("| %s |" % element_key))
    cells = lines[row].split("|")
    assert cells[column + 1] == "  "
    cells[column + 1] = " %s " % story_key
    lines[row] = "|".join(cells)
    write(ws, rel, "\n".join(lines))


def recipe_breakdown_row(ws, domain, stream, slug):
    """## Recipe: BREAKDOWN.md row in .agents/skills/task-new/SKILL.md."""
    values = frontmatter_values((ws / story_rel(domain, stream, slug)).read_text(encoding="utf-8"))
    row = "| story:%s/%s/%s | %s |" % (PROJECT, domain, slug, " | ".join(
        values.get(f, "") for f in ("wave", "scope", "unmapped", "tracker", "depends")))
    rel = "projects/%s/domains/%s/streams/%s/BREAKDOWN.md" % (PROJECT, domain, stream)
    path = ws / rel
    if not path.exists():
        language = workspace_language(ws)
        block = profile(ws).get("breakdown", {})
        title, note, columns = (in_language(block.get(k, BREAKDOWN_DEFAULTS[k]), language)
                                for k in ("title", "note", "columns"))
        write(ws, rel, "# %s stream:%s/%s/%s\n\n%s\n\n| %s |\n|---|---|---|---|---|---|\n"
              % (title, PROJECT, domain, stream, note, " | ".join(columns)))
    lines = path.read_text(encoding="utf-8").split("\n")
    separator = lines.index("|---|---|---|---|---|---|")
    # The skill's order (`-`, digits, letters) equals code point order for slug characters.
    pos = next((i for i in range(separator + 1, len(lines))
                if lines[i].startswith("| story:") and lines[i].split(" | ", 1)[0].rsplit("/", 1)[1] > slug), None)
    if pos is None:
        lines[-1:] = [row, ""]
    else:
        lines.insert(pos, row)
    write(ws, rel, "\n".join(lines))


def _insert_index_line(lines, pos, entry):
    before = lines[pos - 1]
    if before.startswith("  ") and not before.endswith(","):
        lines[pos - 1] = before + ","
    lines.insert(pos, entry + ("," if lines[pos] != "}" else ""))


def recipe_story_index(ws, domain, stream, slug):
    """## Recipe: index entry in .agents/skills/task-new/SKILL.md."""
    rel = ".agents/index.json"
    path = story_rel(domain, stream, slug)
    tracker = frontmatter_values((ws / path).read_text(encoding="utf-8")).get("tracker", "")
    key = "story:%s/%s/%s" % (PROJECT, domain, slug)
    line = '  "%s": "%s"' % (key, path)
    text = (ws / rel).read_text(encoding="utf-8")
    if text == "{}\n":
        lines = ["{", line, "}", ""]
    else:
        lines = text.split("\n")
        stories = [i for i, l in enumerate(lines) if l.startswith('  "story:')]
        others = [i for i, l in enumerate(lines) if l.startswith(('  "adr:', '  "diagram:', '  "mockup:'))]
        if stories:
            pos = next((i for i in stories if lines[i][len('  "'):].split('"', 1)[0] > key), stories[-1] + 1)
        elif others:
            pos = others[-1] + 1
        else:
            pos = lines.index("{") + 1
        _insert_index_line(lines, pos, line)
    if tracker:
        escaped = tracker.replace("\\", "\\\\").replace('"', '\\"')
        last_story = max(i for i, l in enumerate(lines) if l.startswith('  "story:'))
        close = lines.index("}")
        trackers = range(last_story + 1, close)
        assert not any(lines[i].startswith('  "%s":' % escaped) for i in trackers)
        pos = next((i for i in trackers if lines[i][len('  "'):].split('"', 1)[0] > escaped), close)
        _insert_index_line(lines, pos, '  "%s": "%s"' % (escaped, path))
    write(ws, rel, "\n".join(lines))


def _status_bounds(lines, name):
    return lines.index("<!-- status:%s:begin -->" % name), lines.index("<!-- status:%s:end -->" % name)


def _status_row_pair(line):
    """(date, key) of a status row `| [<key>](<path>) | <date> |`: started or recorded, then key."""
    key_cell, started = line[2:-2].split(" | ")
    return started, key_cell[1:].split("](", 1)[0]


def _delete_status_row(lines, name, key):
    """Delete key's row from a grouped status section; a group left without rows goes away whole."""
    begin, end = _status_bounds(lines, name)
    row_line = next(i for i in range(begin + 1, end) if lines[i].startswith("| [%s](" % key))
    heading = max(i for i in range(begin, row_line) if lines[i].startswith("### "))
    group_end = next((i for i in range(row_line + 1, end) if lines[i].startswith("### ")), end)
    if sum(1 for i in range(heading + 1, group_end) if lines[i].startswith("| [")) == 1:
        # One neighbouring blank line goes with the group, so no two blank lines stay together;
        # a sole group between the markers has no blank neighbour at all.
        first = heading - 1 if group_end == end and lines[heading - 1] == "" else heading
        del lines[first:group_end]
    else:
        del lines[row_line]


def recipe_status_start(ws, domain, stream, slug, owner, started):
    """## Recipe: STATUS.md start flip in .agents/skills/task-start/SKILL.md."""
    key = "story:%s/%s/%s" % (PROJECT, domain, slug)
    lines = (ws / "STATUS.md").read_text(encoding="utf-8").split("\n")
    row = "| [%s](%s) | %s |" % (key, story_rel(domain, stream, slug), started)

    # Step 1, `## Waiting`: delete the row; a group left without rows goes away whole.
    _delete_status_row(lines, "waiting", key)

    # Step 2, `## In progress`: insert the row into the owner group.
    begin, end = _status_bounds(lines, "in-progress")
    headings = [i for i in range(begin + 1, end) if lines[i].startswith("### ")]
    group = next((h for h in headings if lines[h] == "### %s" % owner), None)
    if group is None:
        block = ["### %s" % owner, "", "| Task | Started |", "|---|---|", row]
        after = [h for h in headings if lines[h][len("### "):] > owner]
        if after:
            lines[after[0]:after[0]] = block + [""]
        elif headings:
            lines[end:end] = [""] + block
        else:
            lines[begin + 1:begin + 1] = block
    else:
        group_end = next((h for h in headings if h > group), end)
        rows = [i for i in range(group + 1, group_end) if lines[i].startswith("| [")]
        pos = next((i for i in rows if _status_row_pair(lines[i]) > (started, key)), rows[-1] + 1)
        lines[pos:pos] = [row]
    write(ws, "STATUS.md", "\n".join(lines))


def finish_story(ws, domain, stream, slug, owner, started, recorded):
    """Steps 12-13 of .agents/skills/work-record/SKILL.md: the work.md record and the done flip."""
    rel = story_rel(domain, stream, slug)
    text = (ws / rel).read_text(encoding="utf-8")
    for old, new in (("status: in_progress\n", "status: done\n"),
                     ("owner: %s\n" % owner, "owner:\n"),
                     ("started: %s\n" % started, "started:\n")):
        assert text.count(old) == 1, old
        text = text.replace(old, new)
    write(ws, rel, text)
    record = (ws / ".agents/templates/work.md").read_text(encoding="utf-8")
    # The generator reads only `recorded` from work.md; the rest of the record is prose.
    write(ws, rel.rsplit("/", 1)[0] + "/work.md",
          record.replace("YYYY-MM-DD", recorded)
                .replace("<task key>", "story:%s/%s/%s" % (PROJECT, domain, slug))
                .replace("<one-line summary>", "Done."))


def recipe_status_done(ws, domain, stream, slug, recorded):
    """## Recipe: STATUS.md done flip in .agents/skills/work-record/SKILL.md."""
    key = "story:%s/%s/%s" % (PROJECT, domain, slug)
    lines = (ws / "STATUS.md").read_text(encoding="utf-8").split("\n")

    # Step 1, `## In progress`: delete the row; a group left without rows goes away whole.
    _delete_status_row(lines, "in-progress", key)

    # Step 2, `## Done recently`: `<recorded>` is today, the newest date the section keeps.
    begin, end = _status_bounds(lines, "done-recently")
    row = "| [%s](%s) | %s |" % (key, story_rel(domain, stream, slug), recorded)
    rows = [i for i in range(begin + 1, end) if lines[i].startswith("| [")]
    if not rows:
        lines[begin + 1:begin + 1] = ["| Task | Recorded |", "|---|---|", row]
    else:
        same_day = [i for i in rows if _status_row_pair(lines[i])[0] == recorded]
        pos = (next((i for i in same_day if _status_row_pair(lines[i])[1] > key), same_day[-1] + 1)
               if same_day else rows[0])
        lines[pos:pos] = [row]
    write(ws, "STATUS.md", "\n".join(lines))


class Recipes(unittest.TestCase):
    PARAMS = None

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.recipe = create_workspace(self._tmp.name, "recipe", self.PARAMS)
        self.generated = create_workspace(self._tmp.name, "generated", self.PARAMS)
        self.both = (self.recipe, self.generated)

    def generate(self, ws):
        result = run_generate(ws)
        self.assertEqual(result.returncode, 0, result.stderr)

    def assertSameTrees(self):
        self.generate(self.generated)
        left, right = tree_bytes(self.recipe), tree_bytes(self.generated)
        differing = sorted(p for p in set(left) | set(right) if left.get(p) != right.get(p))
        self.assertEqual(differing, [], "paths differ between recipe and generated: %s" % differing)

    def test_repository(self):
        first = {"name": "orders-api", "remote": "git@example.com:t/orders-api.git", "forge": "gitlab",
                 "default_branch": "main", "summary": "Serves orders"}
        second = {"name": "payments-worker", "remote": "git@example.com:t/payments-worker.git",
                  "forge": "github", "default_branch": "develop",
                  "summary": "Consumes payment events and writes postings"}
        for entry in (first, second):
            for ws in self.both:
                add_repository_source(ws, entry)
            recipe_repository(self.recipe, entry)
        self.assertIn("| payments-worker | github | develop |  | Consumes",
                      (self.recipe / "REPOSITORIES.md").read_text(encoding="utf-8"))
        self.assertSameTrees()

    def test_repository_with_kit(self):
        plain = {"name": "orders-api", "remote": "git@example.com:t/orders-api.git", "forge": "gitlab",
                 "default_branch": "main", "summary": "Serves orders"}
        with_kit = {"name": "abs-operations", "remote": "git@example.com:t/abs-operations.git", "forge": "gitlab",
                    "default_branch": "master", "summary": "Operations micro frontend",
                    "kit": {"kind": "mfe", "params": {"MFE": "abs-operations", "BFF": "abs-operations-bff",
                                                      "PREFIX": "ops"}}}
        for entry in (plain, with_kit):
            for ws in self.both:
                add_repository_source(ws, entry)
            recipe_repository(self.recipe, entry)
        self.assertIn("| abs-operations | gitlab | master | mfe | Operations micro frontend |\n",
                      (self.recipe / "REPOSITORIES.md").read_text(encoding="utf-8"))
        self.assertSameTrees()

    def test_adr_into_empty_index(self):
        for ws in self.both:
            write(ws, "docs/adr/0001-use-kafka.md", "# ADR-0001: Use Kafka\n")
        recipe_adr(self.recipe, "0001", "use-kafka")
        self.assertEqual((self.recipe / ".agents/index.json").read_text(encoding="utf-8"),
                         '{\n  "adr:0001": "docs/adr/0001-use-kafka.md"\n}\n')
        self.assertSameTrees()

    def test_adr_after_existing_adr_and_diagram(self):
        for ws in self.both:
            write(ws, "docs/adr/0001-a.md", "# ADR-0001: A\n")
            write(ws, "docs/diagrams/flow.md", "# Flow\n")
            self.generate(ws)
            write(ws, "docs/adr/0002-b.md", "# ADR-0002: B\n")
        recipe_adr(self.recipe, "0002", "b")
        self.assertSameTrees()

    def test_skill(self):
        for ws in self.both:
            write(ws, ".agents/skills/release-notes/SKILL.md",
                  "---\nname: release-notes\ndescription: Writes release notes.\n---\n# Release notes\n")
            write(ws, ".agents/skills/release-notes/examples/a.txt", "example\n")
            (ws / ".agents/skills/release-notes/.DS_Store").write_bytes(b"\x00\x00\x00\x01Bud1")
        recipe_skill(self.recipe, "release-notes")
        self.assertFalse((self.recipe / ".claude/skills/release-notes/.DS_Store").exists())
        self.assertSameTrees()

    def test_agent(self):
        source = ("---\nname: reviewer\ndescription: Reviews diffs: flags risky changes\n---\n"
                  "# Reviewer\nList findings as `path:line message`.\n")
        for ws in self.both:
            write(ws, ".agents/agents/reviewer.md", source)
        recipe_agent(self.recipe, "reviewer")
        self.assertSameTrees()

    def test_rule(self):
        for ws in self.both:
            write(ws, ".agents/rules/sql-style.md", "# SQL style\n\n- Write SQL keywords in upper case.\n")
        recipe_rule(self.recipe, "sql-style")
        self.assertSameTrees()

    def test_map_element_into_empty_map(self):
        for ws in self.both:
            add_domain(ws, "risks")
            add_screen(ws, "risks", "overview", "/risks", "", 1, [("Open alerts", "screen:demo/risks/alerts")])
        recipe_map_element(self.recipe, "risks", "overview")
        self.assertSameTrees()

    def test_map_element_before_existing_with_two_transitions(self):
        for ws in self.both:
            add_domain(ws, "risks")
            add_screen(ws, "risks", "limit", "/risks/limit", "", 1, [("Open card", "screen:demo/risks/limit-card")])
            self.generate(ws)
            # limit-card.md sorts before limit.md ("-" < "."), although its key sorts after.
            add_screen(ws, "risks", "limit-card", "/risks/limit/card", "screen:demo/risks/limit", 2,
                       [("Back", "screen:demo/risks/limit"), ("Show alerts", "screen:demo/risks/alerts")])
        recipe_map_element(self.recipe, "risks", "limit-card")
        self.assertSameTrees()

    def test_map_element_takes_from_column_from_profile(self):
        for ws in self.both:
            set_from_column(ws, {"en": "Source", "ru": "Источник"})
            add_domain(ws, "risks")
            add_screen(ws, "risks", "overview", "/risks", "", 1, [("Open alerts", "screen:demo/risks/alerts")])
        recipe_map_element(self.recipe, "risks", "overview")
        self.assertIn("| %s | " % from_column(self.recipe),
                      (self.recipe / "projects/demo/domains/risks/MAP.md").read_text(encoding="utf-8"))
        self.assertNotIn("| From | ", (self.recipe / "projects/demo/domains/risks/MAP.md").read_text(encoding="utf-8"))
        self.assertSameTrees()

    def test_story_into_empty_breakdown(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            self.generate(ws)
            add_story(ws, "operations", "migration", "bff-defects", 3, unmapped="BFF returns wrong totals")
        recipe_breakdown_row(self.recipe, "operations", "migration", "bff-defects")
        recipe_story_index(self.recipe, "operations", "migration", "bff-defects")
        self.assertSameTrees()

    def test_story_into_non_empty_breakdown(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            add_story(ws, "operations", "migration", "login", 1, scope=["screen:demo/operations/login"])
            add_story(ws, "operations", "migration", "users", 2,
                      scope=["screen:demo/operations/users", "screen:demo/operations/user-view"],
                      depends=["story:demo/operations/login"])
            self.generate(ws)
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"],
                      depends=["story:demo/operations/login"])
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        self.assertSameTrees()

    def test_story_creates_missing_breakdown(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            add_story(ws, "operations", "migration", "login", 1, scope=["screen:demo/operations/login"])
        self.assertFalse((self.recipe / "projects/demo/domains/operations/streams/migration/BREAKDOWN.md").exists())
        recipe_breakdown_row(self.recipe, "operations", "migration", "login")
        recipe_story_index(self.recipe, "operations", "migration", "login")
        self.assertSameTrees()

    def test_story_with_quoted_values(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            self.generate(ws)
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"],
                      tracker="TASK-12")
            rel = story_rel("operations", "migration", "reports")
            text = (ws / rel).read_text(encoding="utf-8")
            text = text.replace("wave: 2\n", 'wave: "2"\n').replace("tracker: TASK-12\n", "tracker: 'TASK-12'\n")
            write(ws, rel, text.replace("  - screen:demo/operations/reports\n", '  - "screen:demo/operations/reports"\n'))
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        self.assertSameTrees()

    def _index_with_adr_and_mockup(self, ws):
        write(ws, "docs/adr/0001-use-kafka.md", "# ADR-0001: Use Kafka\n")
        write(ws, "docs/diagrams/external.json", json.dumps(
            {"diagrams": [{"key": "mockup:operations/login", "url": "https://design.example.org/file/login"}]},
            indent=2) + "\n")

    def test_story_index_entry_without_tracker(self):
        for ws in self.both:
            self._index_with_adr_and_mockup(ws)
            add_stream(ws, "operations", "migration")
            self.generate(ws)
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"])
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        self.assertSameTrees()

    def test_story_index_entry_with_tracker(self):
        for ws in self.both:
            self._index_with_adr_and_mockup(ws)
            add_stream(ws, "operations", "migration", stage="delivery")
            add_story(ws, "operations", "migration", "users", 1, scope=["screen:demo/operations/users"], tracker="TASK-9")
            self.generate(ws)
            # TASK-12 sorts before TASK-9 by characters, so both new lines go above the existing ones.
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"],
                      tracker="TASK-12")
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        self.assertIn('  "TASK-12": "%s",\n' % story_rel("operations", "migration", "reports"),
                      (self.recipe / ".agents/index.json").read_text(encoding="utf-8"))
        self.assertSameTrees()

    def test_story_cell_in_map(self):
        for ws in self.both:
            add_domain(ws, "operations")
            add_screen(ws, "operations", "reports", "/reports", "", 2, [])
            add_screen(ws, "operations", "users", "/users", "", 1, [])
            add_stream(ws, "operations", "migration")
            self.generate(ws)
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"])
            set_screen_story(ws, "operations", "reports", "story:demo/operations/reports")
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        recipe_story_cell(self.recipe, "operations", "screen:demo/operations/reports", "story:demo/operations/reports")
        self.assertSameTrees()

    def test_start_flip_moves_story_from_waiting_to_progress(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            add_story(ws, "operations", "migration", "documents", 1, waiting=True)
            add_story(ws, "operations", "migration", "export", 2, waiting=True)
            self.generate(ws)
            flip_story(ws, "operations", "migration", "documents", "maxim", "2026-09-21")
        recipe_status_start(self.recipe, "operations", "migration", "documents", "maxim", "2026-09-21")
        status = (self.recipe / "STATUS.md").read_text(encoding="utf-8")
        self.assertIn("### maxim\n\n| Task | Started |\n|---|---|\n"
                      "| [story:demo/operations/documents](%s) | 2026-09-21 |"
                      % story_rel("operations", "migration", "documents"), status)
        waiting = status.split("<!-- status:waiting:begin -->")[1].split("<!-- status:waiting:end -->")[0]
        self.assertNotIn("documents", waiting)
        self.assertIn("[story:demo/operations/export]", waiting)
        self.assertSameTrees()

    def test_start_flip_orders_groups_rows_and_empties_the_waiting_group(self):
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            for slug in ("login", "users", "documents", "alerts", "reports"):
                add_story(ws, "operations", "migration", slug, 1, waiting=True)
            self.generate(ws)
        # bob's group lands between anna's and carol's; inside it the rows sort by started date, then key.
        for slug, owner, started in (("login", "anna", "2026-09-01"),
                                     ("users", "carol", "2026-09-02"),
                                     ("documents", "bob", "2026-09-21"),
                                     ("alerts", "bob", "2026-09-19"),
                                     ("reports", "bob", "2026-09-19")):
            for ws in self.both:
                flip_story(ws, "operations", "migration", slug, owner, started)
            recipe_status_start(self.recipe, "operations", "migration", slug, owner, started)
        status = (self.recipe / "STATUS.md").read_text(encoding="utf-8")
        in_progress = status.split("<!-- status:in-progress:begin -->")[1].split("<!-- status:in-progress:end -->")[0]
        self.assertEqual([line[len("### "):] for line in in_progress.split("\n") if line.startswith("### ")],
                         ["anna", "bob", "carol"])
        bob_group = in_progress.split("### bob\n")[1].split("### ")[0]
        self.assertEqual([line[len("| ["):].split("]")[0] for line in bob_group.split("\n")
                          if line.startswith("| [")],
                         ["story:demo/operations/alerts", "story:demo/operations/reports",
                          "story:demo/operations/documents"])
        waiting = status.split("<!-- status:waiting:begin -->")[1].split("<!-- status:waiting:end -->")[0]
        self.assertEqual(waiting.strip(), "")
        self.assertSameTrees()

    def test_done_flip_moves_story_from_progress_to_done_recently(self):
        recorded = datetime.date.today().isoformat()
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            add_story(ws, "operations", "migration", "documents", 1, waiting=True)
            self.generate(ws)
            flip_story(ws, "operations", "migration", "documents", "maxim", "2026-09-21")
        recipe_status_start(self.recipe, "operations", "migration", "documents", "maxim", "2026-09-21")
        for ws in self.both:
            finish_story(ws, "operations", "migration", "documents", "maxim", "2026-09-21", recorded)
        recipe_status_done(self.recipe, "operations", "migration", "documents", recorded)
        status = (self.recipe / "STATUS.md").read_text(encoding="utf-8")
        in_progress = status.split("<!-- status:in-progress:begin -->")[1].split(
            "<!-- status:in-progress:end -->")[0]
        self.assertEqual(in_progress.strip(), "")
        done = status.split("<!-- status:done-recently:begin -->")[1].split("<!-- status:done-recently:end -->")[0]
        self.assertIn("| Task | Recorded |\n|---|---|\n"
                      "| [story:demo/operations/documents](%s) | %s |"
                      % (story_rel("operations", "migration", "documents"), recorded), done)
        self.assertSameTrees()

    def test_done_flip_orders_rows_and_empties_owner_groups(self):
        today = datetime.date.today().isoformat()
        older = (datetime.date.today() - datetime.timedelta(days=2)).isoformat()
        for ws in self.both:
            add_stream(ws, "operations", "migration")
            for slug in ("login", "documents", "alerts", "export"):
                add_story(ws, "operations", "migration", slug, 1, waiting=True)
            self.generate(ws)
        for slug, owner, started in (("login", "anna", "2026-09-18"),
                                     ("documents", "bob", "2026-09-19"),
                                     ("alerts", "bob", "2026-09-18"),
                                     ("export", "carol", "2026-09-17")):
            for ws in self.both:
                flip_story(ws, "operations", "migration", slug, owner, started)
            recipe_status_start(self.recipe, "operations", "migration", slug, owner, started)
        # export is recorded two days ago, the others today: today's rows land above it by key.
        for slug, owner, started, recorded in (("export", "carol", "2026-09-17", older),
                                               ("login", "anna", "2026-09-18", today),
                                               ("documents", "bob", "2026-09-19", today),
                                               ("alerts", "bob", "2026-09-18", today)):
            for ws in self.both:
                finish_story(ws, "operations", "migration", slug, owner, started, recorded)
            recipe_status_done(self.recipe, "operations", "migration", slug, recorded)
        status = (self.recipe / "STATUS.md").read_text(encoding="utf-8")
        in_progress = status.split("<!-- status:in-progress:begin -->")[1].split(
            "<!-- status:in-progress:end -->")[0]
        self.assertEqual(in_progress.strip(), "")
        done = status.split("<!-- status:done-recently:begin -->")[1].split("<!-- status:done-recently:end -->")[0]
        self.assertEqual([line[len("| ["):].split("]")[0] for line in done.split("\n")
                          if line.startswith("| [")],
                         ["story:demo/operations/alerts", "story:demo/operations/documents",
                          "story:demo/operations/login", "story:demo/operations/export"])
        self.assertSameTrees()


class RussianRecipes(Recipes):
    """Every recipe test again, in a workspace whose .agents/kit.json has params.language ru."""
    PARAMS = dict(DEFAULT_PARAMS, language="ru")

    def test_recipes_write_russian_profile_values(self):
        # Guards against a profile without ru values, which would let the tests above pass on English text:
        # every ru value the recipes write must differ from its en value and must appear in the output.
        heading, columns = screen_table(self.recipe)
        table = profile(self.recipe)["elements"][0]["tables"][0]
        breakdown = profile(self.recipe)["breakdown"]
        title = in_language(breakdown["title"], "ru")
        note = in_language(breakdown["note"], "ru")
        b_columns = in_language(breakdown["columns"], "ru")
        self.assertNotEqual(heading, in_language(table["heading"], "en"))
        self.assertNotEqual(columns, in_language(table["columns"], "en"))
        self.assertNotEqual(title, in_language(breakdown["title"], "en"))
        self.assertNotEqual(note, in_language(breakdown["note"], "en"))
        self.assertNotEqual(b_columns, in_language(breakdown["columns"], "en"))
        from_value = from_column(self.recipe)
        self.assertNotEqual(from_value, in_language(profile(self.recipe)["map_doc"]["from_column"], "en"))
        for ws in self.both:
            add_domain(ws, "operations")
            add_screen(ws, "operations", "reports", "/reports", "", 2, [("Назад", "screen:demo/operations/users")])
            add_stream(ws, "operations", "migration")
            add_story(ws, "operations", "migration", "reports", 2, scope=["screen:demo/operations/reports"])
        recipe_map_element(self.recipe, "operations", "reports")
        recipe_breakdown_row(self.recipe, "operations", "migration", "reports")
        recipe_story_index(self.recipe, "operations", "migration", "reports")
        map_text = (self.recipe / "projects/demo/domains/operations/MAP.md").read_text(encoding="utf-8")
        self.assertIn(
            "<!-- map:%s:begin -->\n| %s | %s |\n" % (heading.lower().replace(" ", "-"), from_value, " | ".join(columns)),
            map_text)
        breakdown_text = (self.recipe / "projects/demo/domains/operations/streams/migration/BREAKDOWN.md").read_text(
            encoding="utf-8")
        self.assertTrue(breakdown_text.startswith("# %s stream:" % title))
        self.assertIn(note, breakdown_text)
        for column in b_columns:
            self.assertIn(column, breakdown_text)
        self.assertSameTrees()


if __name__ == "__main__":
    unittest.main()
