import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "kits/workspace/tools"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import json
import tempfile
import unittest

from wslib.common import Context
from wslib.profiles import load_profiles
from workspace_helpers import DEFAULT_PARAMS, create_workspace, run_check, run_generate

PROFILE = ".agents/profiles/ui-migration"
STREAM = "domains/demo/streams/migration"
STREAM_JSON = STREAM + "/stream.json"
MAP_DOC = "domains/demo/MAP.md"
BREAKDOWN = STREAM + "/BREAKDOWN.md"
STORY_DIR = STREAM + "/stories/list"

RU_STORY_SECTIONS = [
    "Заинтересованные стороны",
    "Описание бизнес-потребности",
    "Цель",
    "Функциональные требования",
    "Нефункциональные требования",
    "Задачи внутри стори",
    "Этапы",
    "Открытые вопросы",
]
RU_EPIC_SECTIONS = ["Цель", "Объём", "Критерии успеха", "Вне объёма", "Открытые вопросы", "Целевые пользователи", "Продукт"]
RU_BREAKDOWN_HEAD = (
    "# Разбивка stream:demo/migration\n"
    "\n"
    "Сгенерировано tools/generate.py из stories/*/story.md. Не редактировать.\n"
    "\n"
    "| Стори | Волна | Экраны | Без экрана | Трекер | Зависит от |\n"
    "|---|---|---|---|---|---|\n"
)
EN_BREAKDOWN_HEAD = (
    "# Breakdown of stream:demo/migration\n"
    "\n"
    "Generated by tools/generate.py from stories/*/story.md. Do not edit.\n"
    "\n"
    "| Story | Wave | Scope | Unmapped | Tracker | Depends |\n"
    "|---|---|---|---|---|---|\n"
)


def rule_lines(lines, rule):
    return [line for line in lines if len(line.split(" ")) > 1 and line.split(" ")[1] == rule]


def headings(text):
    return [line for line in text.split("\n") if line.startswith("# ") or line.startswith("## ")]


class WorkspaceWalk(unittest.TestCase):
    """A fresh workspace in LANGUAGE walked to stage map with the profile templates of that language."""

    LANGUAGE = None

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        params = dict(DEFAULT_PARAMS) if self.LANGUAGE is None else dict(DEFAULT_PARAMS, language=self.LANGUAGE)
        self.ws = create_workspace(Path(self._tmp.name).resolve(), params=params)

    def tearDown(self):
        self._tmp.cleanup()

    def read(self, rel):
        return (self.ws / rel).read_text(encoding="utf-8")

    def write(self, rel, text):
        path = self.ws / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def template(self, name, subs):
        """Profile template <name>.<language>.md when the language has one, as a skill picks it."""
        rel = "%s/%s.md" % (PROFILE, name)
        if self.LANGUAGE is not None and (self.ws / PROFILE / ("%s.%s.md" % (name, self.LANGUAGE))).is_file():
            rel = "%s/%s.%s.md" % (PROFILE, name, self.LANGUAGE)
        text = self.read(rel)
        for placeholder, value in subs.items():
            text = text.replace("<%s>" % placeholder, value)
        return text

    def check(self):
        result = run_generate(self.ws)
        self.assertEqual(result.returncode, 0, result.stderr)
        code, lines, stderr = run_check(self.ws)
        self.assertNotIn("Traceback", stderr)
        return code, lines

    def profile(self):
        profiles, findings = load_profiles(Context(self.ws))
        self.assertEqual(findings, [])
        return profiles["ui-migration"]

    def at_goal(self):
        self.write("domains/demo/README.md", self.read(".agents/templates/domain/README.md").replace("<name>", "demo"))
        stream = json.loads(self.read(".agents/templates/stream.json").replace("<domain>", "demo").replace("<stream>", "migration"))
        self.write(STREAM_JSON, json.dumps(stream, indent=2) + "\n")
        epic = self.template("epic", {})
        self.write(STREAM + "/epic.md", epic.replace("<", "").replace(">", ""))

    def at_map(self, transition, trace_row):
        self.at_goal()
        screen = self.template(
            "screen",
            {"domain": "demo", "slug": "list", "route": "list", "section": "demo",
             "spec operation": "getList", "legacy menu label": "List"},
        )
        self.write("domains/demo/map/list.md", screen + transition)
        text = self.template("MAP", {"domain": "demo"})
        header_line = [line for line in text.split("\n") if line.startswith("| ")][0]
        header = header_line + "\n|---|---|---|---|\n"
        self.assertIn(header, text)
        self.write(MAP_DOC, text.replace(header, header + trace_row))
        stream = json.loads(self.read(STREAM_JSON))
        stream.update(stage="map", scope=["screen:demo/list"])
        stream["approvals"].append({"stage": "goal", "by": "owner", "date": "2026-09-01"})
        self.write(STREAM_JSON, json.dumps(stream, indent=2) + "\n")

    def block(self, name):
        text = self.read(MAP_DOC)
        begin, end = "<!-- map:%s:begin -->\n" % name, "<!-- map:%s:end -->" % name
        self.assertIn(begin, text)
        return text.split(begin, 1)[1].split(end, 1)[0]


class RussianWorkspaceTest(WorkspaceWalk):
    LANGUAGE = "ru"

    def story(self, replace=None, docs=True):
        text = self.template("story", {"domain": "demo", "slug": "list", "Название стори": "Список"})
        if replace is not None:
            self.assertIn(replace[0], text)
            text = text.replace(replace[0], replace[1], 1)
        self.write(STORY_DIR + "/story.md", text)
        if docs:
            self.write(STORY_DIR + "/front.md", self.template("front", {"домен": "demo", "название": "Список"}))
            self.write(STORY_DIR + "/api.md", self.template("api", {"домен": "demo"}))

    def test_fresh_workspace_passes_with_one_profile(self):
        self.assertEqual(run_check(self.ws)[:2], (0, []))
        self.assertEqual(sorted(p.name for p in (self.ws / ".agents/profiles").iterdir()), ["ui-migration"])

    def test_profile_resolves_to_russian_values(self):
        profile = self.profile()
        self.assertEqual(
            profile["elements"][0]["tables"],
            [{"heading": "Переходы", "columns": ["Действие", "Цель"], "keys": ["Цель"]}],
        )
        self.assertEqual(profile["story"]["sections"], RU_STORY_SECTIONS)
        self.assertEqual(profile["epic"]["sections"], RU_EPIC_SECTIONS)
        self.assertEqual(
            profile["map_doc"]["tables"],
            [{"heading": "Трасса legacy", "columns": ["Группа legacy", "Пункт legacy", "Маршрут legacy", "Цель"],
              "target": "Цель"}],
        )
        self.assertEqual(profile["map_doc"]["from_column"], "Откуда")
        self.assertEqual(profile["stages"]["map"][2], {"gate": "legacy_traced", "table": "Трасса legacy"})
        self.assertEqual(profile["stages"]["ready"][1], {"gate": "no_open_questions", "section": "Открытые вопросы"})
        self.assertEqual(
            profile["breakdown"],
            {"title": "Разбивка", "note": "Сгенерировано tools/generate.py из stories/*/story.md. Не редактировать.",
             "columns": ["Стори", "Волна", "Экраны", "Без экрана", "Трекер", "Зависит от"]},
        )

    def test_templates_have_the_russian_headings(self):
        expected = {
            "story.ru.md": ["# [СО] <Название стори>"] + ["## " + s for s in RU_STORY_SECTIONS],
            "front.ru.md": ["# Фронт: <домен>", "## Место в интерфейсе", "## Экран «<название>»", "## Права"],
            "api.ru.md": ["# API: <домен>", "## Что переносим", "## Ревью контракта", "## Операции",
                          "## Провайдер", "## Не реализовано"],
            "screen.ru.md": ["## Переходы"],
            "epic.ru.md": ["# <Название эпика>"] + ["## " + s for s in RU_EPIC_SECTIONS],
            "MAP.ru.md": ["# Карта домена <domain>", "## Экраны", "## Переходы", "## Навигация", "## Трасса legacy",
                          "## Решения", "## Открытые вопросы"],
        }
        for name, lines in expected.items():
            self.assertEqual(headings(self.read("%s/%s" % (PROFILE, name))), lines, name)
        screen = self.read(PROFILE + "/screen.ru.md")
        self.assertEqual(screen.split("\n---\n", 1)[0], self.read(PROFILE + "/screen.md").split("\n---\n", 1)[0])
        self.assertIn("## Переходы\n| Действие | Цель |\n|---|---|\n", screen)
        story = self.read(PROFILE + "/story.ru.md")
        self.assertEqual(story.split("\n---\n", 1)[0], self.read(PROFILE + "/story.md").split("\n---\n", 1)[0])
        self.assertIn("| Группа legacy | Пункт legacy | Маршрут legacy | Цель |\n|---|---|---|---|\n",
                      self.read(PROFILE + "/MAP.ru.md"))

    def test_russian_story_with_front_and_api_passes(self):
        self.at_map("| Открыть | screen:demo/list |\n", "| Документы | Список | /docs | screen:demo/list |\n")
        self.story()
        lines = self.check()[1]
        self.assertEqual(rule_lines(lines, "story"), [])

    def test_russian_story_without_front_and_api_passes(self):
        self.at_map("| Открыть | screen:demo/list |\n", "| Документы | Список | /docs | screen:demo/list |\n")
        self.story(docs=False)
        self.assertFalse((self.ws / STORY_DIR / "front.md").exists())
        self.assertFalse((self.ws / STORY_DIR / "api.md").exists())
        self.assertEqual(self.check(), (0, []))

    def test_english_section_in_russian_workspace(self):
        self.at_map("| Открыть | screen:demo/list |\n", "| Документы | Список | /docs | screen:demo/list |\n")
        self.story(replace=("\n## Цель\n", "\n## Goal\n"))
        code, lines = self.check()
        self.assertNotEqual(code, 0)
        self.assertEqual(rule_lines(lines, "story"), [STORY_DIR + "/story.md:1 story missing section Цель"])

    def test_map_stage_passes_and_generates_russian_output(self):
        self.at_map("| Открыть | screen:demo/list |\n", "| Документы | Список | /docs | screen:demo/list |\n")
        self.assertEqual(self.check(), (0, []))
        self.assertIn("| screen:demo/list | /list | place |", self.block("screens"))
        self.assertTrue(self.block("переходы").startswith("| Откуда | Действие | Цель |\n|---|---|---|\n"))
        self.assertIn("| screen:demo/list | Открыть | screen:demo/list |", self.block("переходы"))
        self.assertNotIn("map:transitions", self.read(MAP_DOC))
        self.assertEqual(self.read(BREAKDOWN), RU_BREAKDOWN_HEAD)


class EnglishWorkspaceTest(WorkspaceWalk):
    def test_fresh_workspace_passes(self):
        self.assertEqual(run_check(self.ws)[:2], (0, []))

    def test_profile_resolves_to_english_values(self):
        profile = self.profile()
        self.assertEqual(profile["elements"][0]["tables"][0]["heading"], "Transitions")
        self.assertEqual(
            profile["story"]["sections"],
            ["Goal", "Scope", "Acceptance criteria", "Verification", "Out of scope", "Open questions"],
        )
        self.assertEqual(profile["stages"]["map"][2], {"gate": "legacy_traced", "table": "Legacy trace"})
        self.assertEqual(profile["breakdown"]["title"], "Breakdown of")
        self.assertEqual(profile["map_doc"]["from_column"], "From")

    def test_map_stage_generates_english_output(self):
        self.at_map("| Open | screen:demo/list |\n", "| Docs | List | /docs | screen:demo/list |\n")
        self.assertEqual(self.check(), (0, []))
        self.assertIn("| screen:demo/list | /list | place |", self.block("screens"))
        self.assertTrue(self.block("transitions").startswith("| From | Action | Target |\n|---|---|---|\n"))
        self.assertIn("| screen:demo/list | Open | screen:demo/list |", self.block("transitions"))
        self.assertEqual(self.read(BREAKDOWN), EN_BREAKDOWN_HEAD)


if __name__ == "__main__":
    unittest.main()
