"""Render generated MAP.md tables of domains and BREAKDOWN.md of streams."""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Tuple

from wslib.common import Context
from wslib.model import Workspace
from wslib.profiles import from_column

BREAKDOWN_TITLE = "Breakdown of"
BREAKDOWN_NOTE = "Generated by tools/generate.py from stories/*/story.md. Do not edit."
BREAKDOWN_COLUMNS = ["Story", "Wave", "Scope", "Unmapped", "Tracker", "Depends"]


def _cell(value) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return ", ".join(v for v in value if isinstance(v, str))
    return ""


def _usable(item) -> bool:
    return item.error is None and item.fields is not None


def _table(columns: List[str], rows: List[List[str]]) -> List[str]:
    lines = ["| %s |" % " | ".join(columns), "|" + "---|" * len(columns)]
    lines.extend("| %s |" % " | ".join(row) for row in rows)
    return lines


def marker(name: str) -> Tuple[str, str]:
    """Return the (begin, end) marker lines of a MAP.md block."""
    return "<!-- map:%s:begin -->" % name, "<!-- map:%s:end -->" % name


def _table_name(heading: str) -> str:
    return heading.lower().replace(" ", "-")


def marker_names(spec: dict) -> List[str]:
    """Marker names of an element kind: its element table, then each declared table."""
    return [spec["kind"] + "s"] + [_table_name(t["heading"]) for t in spec.get("tables", [])]


def read_map(ctx: Context, rel: str) -> Optional[str]:
    """Read MAP.md without newline translation so its line endings survive rendering."""
    try:
        with open(str(ctx.root / rel), encoding="utf-8", newline="") as f:
            return f.read()
    except (OSError, UnicodeDecodeError):
        return None


def _is_line(line: str, expected: str) -> bool:
    # Lines come from splitting on "\n", so a CRLF line still carries its "\r"; nothing else is stripped.
    return line == expected or line == expected + "\r"


def _line_index(lines: List[str], expected: str, start: int = 0) -> Optional[int]:
    for i in range(start, len(lines)):
        if _is_line(lines[i], expected):
            return i
    return None


def has_begin_marker(text: str, names: List[str]) -> bool:
    """True when some line of text equals the begin marker of one of names."""
    lines = text.split("\n")
    return any(_line_index(lines, marker(name)[0]) is not None for name in names)


def _kind_profiles(ws: Workspace) -> List[Tuple[dict, dict]]:
    """(spec, declaring profile) per element kind of valid profiles in profile order; the first profile declaring a kind wins."""
    pairs: List[Tuple[dict, dict]] = []
    seen = set()
    for profile in ws.profiles.values():
        for spec in profile["elements"]:
            if spec["kind"] not in seen:
                seen.add(spec["kind"])
                pairs.append((spec, profile))
    return pairs


def kind_specs(ws: Workspace) -> List[dict]:
    """Element kind specs of valid profiles in profile order; the first profile declaring a kind wins."""
    return [spec for spec, _ in _kind_profiles(ws)]


def _domain_blocks(ws: Workspace, domain: str) -> List[Tuple[str, List[str]]]:
    """Return (marker name, table lines) for every expected marker pair of a domain."""
    blocks: List[Tuple[str, List[str]]] = []
    # A domain's element tables belong to no single stream, so the From column follows the profile declaring the kind.
    for spec, profile in _kind_profiles(ws):
        names = marker_names(spec)
        elements = sorted(
            (e for e in ws.element_list if e.domain == domain and e.kind == spec["kind"] and _usable(e)),
            key=lambda e: e.slug + ".md",
        )
        rows = [[_cell(e.fields.get(f)) for f in spec["fields"]] for e in elements]
        blocks.append((names[0], _table(spec["fields"], rows)))
        for name, table in zip(names[1:], spec.get("tables", [])):
            heading, columns = table["heading"], table["columns"]
            table_rows = []
            for element in elements:
                parsed_columns, parsed_rows, _ = element.tables.get(heading, (None, [], None))
                if parsed_columns is None:
                    continue
                for _, cells in parsed_rows:
                    # Cells are picked by column name so a reordered source table still lands in profile order.
                    picked = [cells[parsed_columns.index(c)] if c in parsed_columns else "" for c in columns]
                    table_rows.append([element.key] + picked)
            blocks.append((name, _table([from_column(profile)] + columns, table_rows)))
    return blocks


def _render_map(text: str, blocks: List[Tuple[str, List[str]]]) -> Optional[bytes]:
    if not has_begin_marker(text, [name for name, _ in blocks]):
        return None
    lines = text.split("\n")
    cr = "\r" if "\r\n" in text else ""
    for name, table in blocks:
        begin, end = marker(name)
        start = _line_index(lines, begin)
        stop = None if start is None else _line_index(lines, end, start + 1)
        if stop is None:
            continue
        lines = lines[: start + 1] + [line + cr for line in table] + lines[stop:]
    return "\n".join(lines).encode("utf-8")


def _render_breakdown(stream, profile: Optional[dict]) -> bytes:
    # Streams with an unknown or invalid profile still get a breakdown, with the defaults.
    block = (profile or {}).get("breakdown", {})
    title = block.get("title", BREAKDOWN_TITLE)
    note = block.get("note", BREAKDOWN_NOTE)
    columns = block.get("columns", BREAKDOWN_COLUMNS)
    rows = []
    for story in sorted(stream.stories.values(), key=lambda s: s.slug):
        if not _usable(story):
            continue
        f = story.fields
        rows.append(
            [story.key]
            + [_cell(f.get(name)) for name in ("wave", "scope", "unmapped", "tracker", "depends")]
        )
    head = ["# %s %s" % (title, stream.key), "", note, ""]
    return ("\n".join(head + _table(columns, rows)) + "\n").encode("utf-8")


def render(root) -> Dict[str, bytes]:
    """Return rendered domain MAP.md files and stream BREAKDOWN.md files keyed by POSIX path."""
    ctx = Context(Path(root))
    ws = Workspace(ctx)
    out: Dict[str, bytes] = {}
    for domain, rel in sorted(ws.map_docs.items()):
        text = read_map(ctx, rel)
        if text is None:
            continue
        data = _render_map(text, _domain_blocks(ws, domain))
        if data is not None:
            out[rel] = data
    for stream in ws.streams:
        if stream.data is None:
            continue
        out["domains/%s/streams/%s/BREAKDOWN.md" % (stream.domain, stream.name)] = _render_breakdown(
            stream, ws.profiles.get(stream.profile_name)
        )
    return out
